services:
  - type: web
    name: storycraft-ai
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0

    envVars:
      - key: PYTHON_VERSION
        value: "3.10.11"
      - key: GOOGLE_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
